import Head from 'next/head';
import Header from '../page_components/Header';
import style from '@/styles/layout.module.css';
import FlipCard from '@/components/cards/FlipCard/FlipCard';

export default function Cards() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<meta
					name='viewport'
					content='width=device-width, initial-scale=1'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main className={style.wrapper}>
				<div className={style.container}>
					<Header />
					<section>
                        <FlipCard />
                        <FlipCard />
                        <FlipCard />
                        <FlipCard />
                    </section>
				</div>
			</main>
		</>
	);
}
