import Head from 'next/head';
import Header from '@/page_components/PageHeader';
import style from '@/styles/layout.module.css';
import MenuLink from '@/page_components/MenuLink';

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<meta
					name='viewport'
					content='width=device-width, initial-scale=1'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main className={style.wrapper}>
				<div className={style.container}>
					<Header />
					<section>
						<h2>Table of Contents</h2>
						<ul>
							<MenuLink
								text='Card Components'
								destination='/cards'
							/>
						</ul>
					</section>
				</div>
			</main>
		</>
	);
}
